# DOCKERFILE PARA EL ENTORNO DE DESARROLLO

#Empleamos la imagen del repositorio oficial de Docker para Node
FROM node:17.8-bullseye

#Se expone el puerto 3000 para poder consultar el sitio desde el pc host
EXPOSE 3000